### ISSUE TITLE
Does anyone try to export an unfine-tuned BERT model?

### ISSUE THREAD

**Issue by stevewyl** [bigboNed3/bert_serving#7]
Hi, I follow this [repo](https://github.com/xu-song/bert-as-language-model) to service bert model as language model. So I try to export the original BERT model as SavedModel but failed. The error messages are as follwoed:

Traceback (most recent call last):
  File "export_lm_predictor.py", line 136, in <module>
    './exported_model', serving_input_receiver_fn(max_seq_len, 20))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 734, in export_saved_model
    strip_default_attrs=True)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 663, in export_savedmodel
    mode=model_fn_lib.ModeKeys.PREDICT)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 789, in _export_saved_model_for_mode
    strip_default_attrs=strip_default_attrs)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 878, in _export_all_saved_models
    raise ValueError("Couldn't find trained model at %s." % self._model_dir)
ValueError: Couldn't find trained model at ../bert_models/chinese_L-12_H-768_A-12.

I guess that there is no graph.pbtxt and checkpoint files in the original model dir. Does anyone have any ideas? Thanks!

[edit]
I specify the checkpoint_path parameter in export_saved_model function. By the way, I
create the estimator using tf.estimator.Estimator. Then I got a new error:
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory ../bert_models/chinese_L-12_H-768_A-12
So we must got checkpoint file in the original BERT model directory?

**Comment by stevewyl** [comment]
Hi, all! I found an easiest way to export original bert model to SavedModel. 

```python 
# load the checkpoint from bert
# create an estimator which contains original bert model and some other ops if you want
estimator = ...
save_hook = tf.train.CheckpointSaverHook(FLAGS.output_dir, save_secs=1)
estimator.predict(input_fn=predict_input_fn, hooks=[save_hook])
# now you will get graph.pbtxt which is used in SavedModel, and then
estimator.export_savedmodel(...)
```
